import {categories} from './data.js';

const app=document.querySelector('#app'),toast=document.querySelector('#toast');
const USERS='fq-users-v2',SESSION='fq-session-v2',DATA='fuocoquiz-data-v1',CONFIG='q400vvf-config-v1',ACTIVE_QUIZZES='q400vvf-active-quizzes-v1';
let users=JSON.parse(localStorage.getItem(USERS)||'[]'),currentUser=null,official=[],imported=JSON.parse(localStorage.getItem(DATA)||'[]');
const DEFAULT_EXAM_PLAN={storia:8,logica:11,insiemi:1,fisica:6,chimica:6,informatica:4,inglese:4,brani:0};
const EXAM_ORDER=['storia','logica','insiemi','fisica','chimica','informatica','inglese','brani'];
let examConfig=JSON.parse(localStorage.getItem(CONFIG)||'null')||{examPlan:{...DEFAULT_EXAM_PLAN}};
let quiz=null,timerHandle=null,deferredInstall=null,updateCheckedFor=null;
const EXAM_SECONDS=40*60;
const allQuestions=()=>[...official,...imported];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const notify=m=>{toast.textContent=m;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2300)};
const portableSync=()=>fetch('./api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({users,imported,config:examConfig})}).catch(()=>{});
const saveUsers=()=>{localStorage.setItem(USERS,JSON.stringify(users));portableSync()};
const hash=async(s)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(b=>b.toString(16).padStart(2,'0')).join('');
const userRecord=()=>users.find(u=>u.id===currentUser?.id);
const userState=()=>{const u=userRecord();u.state??={};u.state.progress??={};u.state.sessions??=[];u.state.categoryCursor??={};u.state.examCursor??={};u.state.examCount??=0;u.state.quizGenerationCount??=0;u.state.quizRotation??={};return u.state};
const persist=()=>{saveUsers()};
const progressFor=id=>userState().progress[id]||{attempts:0,correct:0,wrong:0,skipped:0,status:'unanswered'};
const catName=id=>categories.find(c=>c.id===id)?.name||id;
const examPlan=()=>EXAM_ORDER.map(id=>[id,Math.max(0,Number(examConfig.examPlan?.[id])||0)]).filter(([,count])=>count>0);
const seedNumber=value=>{let h=2166136261;for(const char of String(value)){h^=char.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
const seededRandom=seed=>{let state=seedNumber(seed)||1;return()=>{state+=0x6D2B79F5;let n=state;n=Math.imul(n^n>>>15,n|1);n^=n+Math.imul(n^n>>>7,n|61);return((n^n>>>14)>>>0)/4294967296}};
function shuffleWithSeed(items,seed){const out=[...items],random=seededRandom(seed);for(let i=out.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out}
function createQuizSeed(kind){const st=userState();st.quizGenerationCount=(Number(st.quizGenerationCount)||0)+1;const now=new Date();return `${now.toISOString()}|${now.getTime()}|${performance.now().toFixed(3)}|${currentUser.id}|${st.quizGenerationCount}|${kind}`}
function takeRotating(source,count,track,cat,sessionSeed){const target=Math.min(Math.max(0,count),source.length);if(!target)return[];const st=userState(),key=`${track}:${cat}`;let rotation=st.quizRotation[key];if(!rotation||rotation.size!==source.length)rotation={seed:`${sessionSeed}|${key}|cycle-0`,cursor:0,cycle:0,size:source.length};const out=[],used=new Set();while(out.length<target){const deck=shuffleWithSeed(source,rotation.seed);while(rotation.cursor<deck.length&&out.length<target){const q=deck[rotation.cursor++];if(!used.has(q.id)){used.add(q.id);out.push(q)}}if(rotation.cursor>=deck.length&&out.length<target){rotation.cycle++;rotation.seed=`${sessionSeed}|${key}|cycle-${rotation.cycle}|${new Date().toISOString()}`;rotation.cursor=0}}st.quizRotation[key]=rotation;return out}
const activeQuizMap=()=>{try{return JSON.parse(localStorage.getItem(ACTIVE_QUIZZES)||'{}')}catch{return{}}};
const isTimedFortyQuiz=(value=quiz)=>value?.kind==='exam'||value?.mode==='guided-exam';
const remainingFor=value=>Math.min(EXAM_SECONDS,Math.max(0,EXAM_SECONDS-Math.floor((Date.now()-Number(value.startedAt))/1000)));
function timerMarkup(){return `<div class="exam-timer" data-exam-timer role="timer" aria-label="Tempo rimasto: ${formatTime(quiz.remaining)}"><span class="exam-timer-label">Tempo rimasto</span><strong data-exam-time>${formatTime(quiz.remaining)}</strong><span class="exam-timer-note">La prova termina automaticamente a 00:00</span></div>`}
function updateTimerDisplay(){const value=formatTime(quiz?.remaining??0);app.querySelectorAll('[data-exam-time]').forEach(element=>element.textContent=value);app.querySelectorAll('[data-exam-timer]').forEach(element=>{element.setAttribute('aria-label',`Tempo rimasto: ${value}`);element.classList.toggle('warning',quiz.remaining<=300&&quiz.remaining>60);element.classList.toggle('danger',quiz.remaining<=60)})}
function tickFortyMinuteTimer(){if(!isTimedFortyQuiz()||quiz.finished){clearInterval(timerHandle);return}quiz.remaining=remainingFor(quiz);updateTimerDisplay();if(quiz.remaining===0){clearInterval(timerHandle);quiz.kind==='exam'?finishExam('timeout'):finishGuided('timeout')}}
function startFortyMinuteTimer(){clearInterval(timerHandle);tickFortyMinuteTimer();if(quiz&&!quiz.finished&&quiz.remaining>0)timerHandle=setInterval(tickFortyMinuteTimer,1000)}
function saveActiveQuiz(){if(!currentUser||!isTimedFortyQuiz()||quiz.finished)return;quiz.remaining=remainingFor(quiz);const snapshot=JSON.parse(JSON.stringify(quiz)),active=activeQuizMap();active[currentUser.id]=snapshot;localStorage.setItem(ACTIVE_QUIZZES,JSON.stringify(active));userState().activeQuiz=snapshot;saveUsers()}
function clearActiveQuiz(){if(!currentUser)return;const active=activeQuizMap();delete active[currentUser.id];localStorage.setItem(ACTIVE_QUIZZES,JSON.stringify(active));delete userState().activeQuiz;saveUsers()}
function resumeActiveQuiz(){if(!currentUser)return false;const saved=activeQuizMap()[currentUser.id]||userState().activeQuiz;if(!saved)return false;if(!isTimedFortyQuiz(saved)||!Array.isArray(saved.pool)||saved.pool.length!==40||!Number.isInteger(saved.index)||saved.index<0||saved.index>=saved.pool.length||!Number.isFinite(Number(saved.startedAt))){clearActiveQuiz();return false}quiz=saved;quiz.finished=false;quiz.remaining=remainingFor(quiz);if(quiz.remaining===0){quiz.kind==='exam'?finishExam('timeout'):finishGuided('timeout');return true}quiz.kind==='exam'?renderQuestion():renderGuided();startFortyMinuteTimer();return true}

function nav(route){document.querySelectorAll('.bottom-nav a').forEach(a=>a.classList.toggle('active',a.dataset.route===route));window.scrollTo({top:0,behavior:'instant'})}
function setHeader(){const top=document.querySelector('.topbar');top.querySelectorAll('.account').forEach(x=>x.remove());if(currentUser){const wrap=document.createElement('div');wrap.className='account';wrap.innerHTML=`<span>${esc(currentUser.name)}${currentUser.role==='admin'?' · Admin':''}</span><button class="ghost compact update-check-button" data-update-check>Aggiornamenti</button><button class="ghost compact" data-logout>Esci</button>`;top.append(wrap);wrap.querySelector('[data-update-check]').onclick=()=>checkForUpdates(true);wrap.querySelector('[data-logout]').onclick=logout}}
function routeTo(h){location.hash=h}
function loginView(){nav('home');setHeader();document.querySelector('.bottom-nav').classList.add('hidden');const first=!users.length;app.innerHTML=`<section class="auth-shell"><div class="auth-copy"><div class="eyebrow">FuocoQuiz</div><h1>${first?'Crea il primo amministratore':'Bentornato'}</h1><p>${first?'Il primo account gestirà gli utenti. I dati restano su questo dispositivo.':'Accedi per ritrovare progressi, domande da ripetere e simulazioni.'}</p></div><form class="card auth-card" id="authForm"><label>Nome utente<input name="username" autocomplete="username" required></label>${first?'<label>Nome visualizzato<input name="name" required></label>':''}<label>Password<input name="password" type="password" autocomplete="current-password" minlength="6" required></label><button class="primary" type="submit">${first?'Crea amministratore':'Accedi'}</button><p class="meta">${first?'La password deve avere almeno 6 caratteri.':'Gli account sono creati da un amministratore.'}</p></form></section>`;app.querySelector('#authForm').onsubmit=first?bootstrapAdmin:login}
async function bootstrapAdmin(e){e.preventDefault();const f=new FormData(e.currentTarget),username=String(f.get('username')).trim().toLowerCase();if(!username)return;const u={id:crypto.randomUUID(),username,name:String(f.get('name')).trim(),role:'admin',passwordHash:await hash(String(f.get('password'))),createdAt:new Date().toISOString(),active:true,state:{progress:{},sessions:[],categoryCursor:{},examCursor:{},examCount:0}};users=[u];saveUsers();signIn(u)}
async function login(e){e.preventDefault();const f=new FormData(e.currentTarget),u=users.find(x=>x.username===String(f.get('username')).trim().toLowerCase());if(!u||!u.active||u.passwordHash!==await hash(String(f.get('password'))))return notify('Credenziali non valide');signIn(u)}
function signIn(u){currentUser={id:u.id,name:u.name,role:u.role};sessionStorage.setItem(SESSION,u.id);document.querySelector('.bottom-nav').classList.remove('hidden');setHeader();routeTo('home');router();checkForUpdates(false)}
function logout(){clearInterval(timerHandle);quiz=null;currentUser=null;updateCheckedFor=null;sessionStorage.removeItem(SESSION);location.hash='login';loginView()}

function showUpdateNotice(info){document.querySelector('[data-update-dialog]')?.remove();const dialog=document.createElement('div');dialog.className='update-dialog-backdrop';dialog.dataset.updateDialog='';dialog.innerHTML=`<section class="card update-dialog" role="dialog" aria-modal="true" aria-labelledby="updateTitle"><div class="eyebrow">Aggiornamento disponibile</div><h2 id="updateTitle">Quiz 400 VVF 2026 ${esc(info.latestVersion)}</h2><p>È disponibile una versione più recente della ${esc(info.currentVersion)} installata.</p><p><b>I tuoi dati non andranno persi:</b> prima dell’installazione viene creato un backup automatico e la cartella <i>portable-data</i> resta intatta.</p><div class="quiz-actions"><button class="primary" data-update-now>Aggiorna ora</button><button class="ghost" data-update-close>Più tardi</button>${info.releaseUrl?`<a class="button ghost" href="${esc(info.releaseUrl)}" target="_blank" rel="noopener">Note della release</a>`:''}</div></section>`;document.body.append(dialog);dialog.querySelector('[data-update-now]').onclick=()=>startInAppUpdate(info,dialog);dialog.querySelector('[data-update-close]').onclick=()=>dialog.remove();dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.remove()})}
async function startInAppUpdate(info,dialog){const panel=dialog.querySelector('.update-dialog');panel.innerHTML=`<div class="update-spinner" aria-hidden="true"></div><div class="eyebrow">Aggiornamento in corso</div><h2>Installazione della versione ${esc(info.latestVersion)}</h2><p>Non chiudere questa pagina. L’app crea il backup, installa la nuova versione e si riavvia automaticamente.</p><p class="meta" data-update-progress>Avvio dell’aggiornamento…</p>`;try{const response=await fetch('./api/update-start',{method:'POST',cache:'no-store'});if(response.status===409){panel.querySelector('[data-update-progress]').textContent='L’app risulta già aggiornata. Ricarico la pagina…';setTimeout(()=>location.reload(),900);return}if(!response.ok)throw Error();panel.querySelector('[data-update-progress]').textContent='Download e installazione in corso…';await waitForUpdatedApp(info.latestVersion,panel)}catch{panel.innerHTML=`<div class="eyebrow">Aggiornamento non avviato</div><h2>Riprova tra poco</h2><p>Controlla la connessione oppure usa il file Aggiorna incluso nella cartella dell’app.</p><div class="quiz-actions"><button class="primary" data-update-close>Chiudi</button></div>`;panel.querySelector('[data-update-close]').onclick=()=>dialog.remove()}}
async function waitForUpdatedApp(expectedVersion,panel){const deadline=Date.now()+300000;while(Date.now()<deadline){await new Promise(resolve=>setTimeout(resolve,1800));try{const response=await fetch(`./api/update-check?t=${Date.now()}`,{cache:'no-store'});if(!response.ok)continue;const status=await response.json();if(status.currentVersion===expectedVersion&&!status.updateAvailable){panel.querySelector('[data-update-progress]').textContent='Aggiornamento completato. Ricarico l’app…';location.replace(`./?updated=${Date.now()}#home`);return}}catch{}}throw Error('timeout')}
async function checkForUpdates(manual=false){if(!currentUser)return;if(!manual&&updateCheckedFor===currentUser.id)return;if(!manual)updateCheckedFor=currentUser.id;notify(manual?'Controllo aggiornamenti…':'Controllo automatico aggiornamenti…');try{const response=await fetch(`./api/update-check?t=${Date.now()}`,{cache:'no-store'});if(!response.ok)throw Error();const info=await response.json();if(info.updateAvailable)showUpdateNotice(info);else notify(`Versione ${info.currentVersion}: l’app è aggiornata`)}catch{notify('Controllo aggiornamenti non disponibile')}}

function summary(){const vals=Object.values(userState().progress);return {answered:vals.filter(x=>x.attempts).length,known:vals.filter(x=>x.status==='known').length,review:vals.filter(x=>x.status==='review').length,unknown:vals.filter(x=>x.status==='unknown').length}}
function home(){nav('home');const s=summary();app.innerHTML=`<section class="hero"><div class="eyebrow">400 Vigili del Fuoco · 11.070 quesiti</div><h1>Studia tutto. Ricorda meglio.</h1><p>Segui ogni materia nell’ordine originale, riprendi da dove eri arrivato e concentra il ripasso sui punti deboli.</p><div class="hero-actions"><a class="button secondary" href="#categories">Continua un argomento</a><a class="button ghost light" href="#simulation">Prova 40/40</a></div></section><div class="section-head"><h2>La tua preparazione</h2></div><div class="stat-row four"><div class="card stat"><strong>${s.answered}</strong><span class="meta">Fatte</span></div><div class="card stat"><strong>${s.known}</strong><span class="meta">Le so</span></div><div class="card stat"><strong>${s.review}</strong><span class="meta">Ripetere</span></div><div class="card stat"><strong>${s.unknown}</strong><span class="meta">Non so</span></div></div><div class="quick-grid"><a class="card quick" href="#review/review"><b>Da ripetere</b><span>Rivedi quelle incerte</span></a><a class="card quick" href="#review/unknown"><b>Non le so</b><span>Lavora sugli errori</span></a><a class="card quick" href="#review/unanswered"><b>Non risposte</b><span>Completa la banca dati</span></a><a class="card quick accent" href="#simulation"><b>Simulazione</b><span>40 domande · 40 minuti</span></a></div>${currentUser.role==='admin'?'<div class="section-head"><h2>Amministrazione</h2></div><a class="card category" href="#settings"><h3>Impostazioni e utenti</h3><p class="meta">Gestisci account, prove, backup e aggiornamenti.</p></a>':''}`}
function categoryCards(){return `<div class="grid">${categories.map(c=>{const qs=allQuestions().filter(q=>q.category===c.id),done=qs.filter(q=>progressFor(q.id).attempts).length,p=Math.round(done/qs.length*100);return `<a class="card category" href="#category/${c.id}"><div class="cat-icon">${c.icon}</div><h3>${c.name}</h3><div class="meta">${done.toLocaleString('it')}/${qs.length.toLocaleString('it')} completate</div><div class="progress"><span style="width:${p}%"></span></div><small>${p}% · riprendi dalla n. ${Math.min(done+1,qs.length)}</small></a>`}).join('')}</div>`}
function categoriesView(){nav('categories');app.innerHTML=`<div class="section-head"><div><div class="eyebrow">Percorso completo e ordinato</div><h1>Tutte le materie</h1></div></div>${categoryCards()}`}
function categoryView(id){nav('categories');const c=categories.find(x=>x.id===id);if(!c)return categoriesView();const qs=allQuestions().filter(q=>q.category===id),done=qs.filter(q=>progressFor(q.id).attempts).length;app.innerHTML=`<div class="section-head"><div><div class="eyebrow">${done}/${qs.length} completate</div><h1>${c.name}</h1></div></div><div class="card"><h2>Percorso completo</h2><p>Le domande vengono presentate nell’ordine originale. Puoi interrompere e riprendere dalla prima non risposta.</p><div class="quiz-actions"><button class="primary" data-resume>${done?'Riprendi dalla prima non fatta':'Inizia dalla domanda 1'}</button><button class="ghost" data-start>Ricomincia dalla n. 1</button></div></div><div class="card guided-card"><div class="mode-title"><span class="mode-icon">✓</span><div><h2>Quiz guidato</h2><p>Stile quiz ufficiale, con esito, risposta corretta e spiegazione subito dopo ogni risposta.</p></div></div><div class="guided-options"><button class="secondary" data-guided="15">15 domande</button><button class="secondary" data-guided="30">30 domande</button><button class="secondary" data-guided="50">50 domande</button></div></div><div class="filter-row"><button class="status-chip known" data-filter="known">Le so</button><button class="status-chip review" data-filter="review">Da ripetere</button><button class="status-chip unknown" data-filter="unknown">Non le so</button><button class="status-chip unanswered" data-filter="unanswered">Non risposte</button></div>`;app.querySelector('[data-resume]').onclick=()=>startCategory(id,'resume');app.querySelector('[data-start]').onclick=()=>startCategory(id,'start');app.querySelectorAll('[data-guided]').forEach(b=>b.onclick=()=>startGuided(id,+b.dataset.guided));app.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>startFiltered(id,b.dataset.filter))}
function startCategory(cat,mode){const pool=allQuestions().filter(q=>q.category===cat);let index=0;if(mode==='resume'){const found=pool.findIndex(q=>!progressFor(q.id).attempts);index=found<0?0:found}quiz={kind:'study',pool,index,history:{},selected:null};renderQuestion()}
function startGuided(cat,count){const seed=createQuizSeed(`guided-${cat}`),source=allQuestions().filter(q=>q.category===cat),selected=takeRotating(source,count,'guided-category',cat,seed),pool=shuffleWithSeed(selected,`${seed}|questions`).map(q=>shuffleGuidedAnswers(q,`${seed}|answers|${q.id}`));persist();quiz={kind:'guided',pool,index:0,history:{},selected:null,generatedAt:new Date().toISOString()};renderGuided()}
function shuffleGuidedAnswers(q,seed=`${Date.now()}|${q.id}`){const indexed=shuffleWithSeed(q.answers.map((text,index)=>({text,index})),seed);return {...q,answers:indexed.map(x=>x.text),correct:indexed.findIndex(x=>x.index===q.correct)}}
function renderGuided(){const q=quiz.pool[quiz.index],h=quiz.history[q.id],selected=h?.choice??null;app.innerHTML=`<div class="trainer-title">Esercitazione in modalità Trainer</div>${quiz.mode==='guided-exam'?timerMarkup():''}<div class="quiz-head"><strong>Domanda n.${quiz.index+1} di ${quiz.pool.length} - ${catName(q.category)}</strong><span>${quiz.index+1}/${quiz.pool.length}</span></div><h1 class="question">${esc(q.text)}</h1>${q.image?`<img class="question-image" src="${esc(q.image)}" alt="Diagramma del quesito">`:''}<div class="answers">${q.answers.map((a,i)=>`<button class="answer ${h?(i===q.correct?'correct':i===selected?'wrong':''):''}" data-guided-answer="${i}" ${h?'disabled':''}><span class="letter">${String.fromCharCode(65+i)}</span><span>${esc(a)}</span></button>`).join('')}</div>${h&&!h.blank?`<div class="feedback trainer-feedback"><strong>${h.correct?'Risposta ESATTA!':`Risposta SBAGLIATA! La risposta corretta era la ${String.fromCharCode(65+q.correct)}.`}</strong><div class="trainer-explanation"><h3>SPIEGAZIONE</h3><p>${q.explanation?esc(q.explanation):'Spiegazione non disponibile per questo quesito.'}</p></div></div>`:''}<div class="quiz-actions nav-actions">${quiz.index>0?'<button class="ghost" data-guided-prev>← Indietro</button>':''}${!h?'<button class="ghost" data-guided-skip>Tralascia domanda</button>':''}${h?`<button class="primary" data-guided-next>${quiz.index===quiz.pool.length-1?'Termina':'Continua →'}</button>`:''}</div>`;app.querySelectorAll('[data-guided-answer]').forEach(b=>b.onclick=()=>guidedAnswer(+b.dataset.guidedAnswer));app.querySelector('[data-guided-prev]')?.addEventListener('click',guidedPrevious);app.querySelector('[data-guided-skip]')?.addEventListener('click',guidedSkip);app.querySelector('[data-guided-next]')?.addEventListener('click',guidedNext)}
function guidedAnswer(choice){const q=quiz.pool[quiz.index],ok=choice===q.correct,p=progressFor(q.id);p.attempts++;if(ok){p.correct++;p.status=p.correct>=2&&p.wrong===0?'known':'review'}else{p.wrong++;p.status='unknown'}p.lastAt=new Date().toISOString();userState().progress[q.id]=p;quiz.history[q.id]={choice,blank:false,correct:ok,q};isTimedFortyQuiz()?saveActiveQuiz():persist();renderGuided()}
function guidedSkip(){const q=quiz.pool[quiz.index],p=progressFor(q.id);p.skipped++;if(!p.attempts)p.status='unanswered';p.lastAt=new Date().toISOString();userState().progress[q.id]=p;quiz.history[q.id]={choice:null,blank:true,correct:false,q};persist();guidedNext()}
function guidedPrevious(){if(quiz.index>0){quiz.index--;saveActiveQuiz();renderGuided()}}
function guidedNext(){quiz.index++;if(quiz.index>=quiz.pool.length)return finishGuided();saveActiveQuiz();renderGuided()}
function finishGuided(){if(!quiz||quiz.finished)return;quiz.finished=true;const rows=quiz.pool.map(q=>quiz.history[q.id]||{choice:null,blank:true,correct:false,q}),correct=rows.filter(x=>x.correct).length,wrong=rows.filter(x=>!x.correct&&!x.blank).length,blank=rows.filter(x=>x.blank).length,score=scoreFor(correct,wrong);userState().sessions.push({type:'guided',at:new Date().toISOString(),correct,wrong,blank,score});persist();app.innerHTML=resultCard('Prova guidata completata',correct,wrong,blank,'<a class="button primary" href="#simulation">Nuova prova</a><a class="button ghost" href="#stats">Statistiche</a>')+reviewReport(rows);window.scrollTo({top:0,behavior:'instant'})}
function startFiltered(cat,status){const pool=allQuestions().filter(q=>(cat==='all'||q.category===cat)&&progressFor(q.id).status===status);if(!pool.length)return notify('Nessuna domanda in questo gruppo');quiz={kind:'study',pool,index:0,history:{},selected:null,filter:status};renderQuestion()}
function reviewView(status){nav('stats');startFiltered('all',status)}

function renderQuestion(){const q=quiz.pool[quiz.index],p=progressFor(q.id),selected=quiz.selected,isStudy=quiz.kind==='study';app.innerHTML=`${!isStudy?timerMarkup():''}<div class="quiz-head"><div><span class="meta">${isStudy?'Studio ordinato':'Simulazione a tempo'}</span><br><strong>${catName(q.category)}</strong></div><strong>${quiz.index+1}/${quiz.pool.length}</strong></div><div class="progress"><span style="width:${(quiz.index+1)/quiz.pool.length*100}%"></span></div><h1 class="question">${esc(q.text)}</h1>${q.image?`<img class="question-image" src="${esc(q.image)}" alt="Diagramma del quesito">`:''}<div class="answers">${q.answers.map((a,i)=>`<button class="answer ${selected!==null&&isStudy?(i===q.correct?'correct':i===selected?'wrong':''):selected===i?'picked':''}" data-answer="${i}" ${selected!==null&&isStudy?'disabled':''}><span class="letter">${String.fromCharCode(65+i)}</span><span>${esc(a)}</span></button>`).join('')}</div>${selected!==null&&isStudy?`<div class="feedback"><strong>${selected===q.correct?'Risposta corretta':'Risposta errata'}</strong><p>${q.explanation?esc(q.explanation):'Spiegazione non disponibile per questo quesito.'}</p><p>Come la consideri?</p><div class="mastery"><button class="status-chip known" data-status="known">La so</button><button class="status-chip review" data-status="review">Da ripetere</button><button class="status-chip unknown" data-status="unknown">Non la so</button></div></div>`:''}<div class="quiz-actions nav-actions">${quiz.index>0?'<button class="ghost" data-prev>← Indietro</button>':''}<button class="ghost" data-skip>${isStudy?'Segna non risposta':'Lascia in bianco'}</button>${selected!==null&&isStudy?'<button class="primary" data-next>Prossima →</button>':''}${!isStudy?'<button class="primary" data-exam-next>Conferma e avanti →</button>':''}</div><div class="question-state">Stato attuale: <b>${statusLabel(p.status)}</b></div>`;app.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>selectAnswer(+b.dataset.answer));app.querySelector('[data-prev]')?.addEventListener('click',previous);app.querySelector('[data-skip]').onclick=skip;app.querySelector('[data-next]')?.addEventListener('click',next);app.querySelector('[data-exam-next]')?.addEventListener('click',examNext);app.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>markStatus(b.dataset.status))}
function selectAnswer(choice){if(quiz.kind==='study'){quiz.selected=choice;recordStudy(choice);renderQuestion()}else{quiz.selected=choice;app.querySelectorAll('.answer').forEach((b,i)=>b.classList.toggle('picked',i===choice));saveActiveQuiz()}}
function recordStudy(choice){const q=quiz.pool[quiz.index],p=progressFor(q.id),ok=choice===q.correct;if(!quiz.history[q.id]){p.attempts++;ok?p.correct++:p.wrong++}p.status=ok?(p.correct>=2&&p.wrong===0?'known':'review'):'unknown';p.lastAt=new Date().toISOString();userState().progress[q.id]=p;quiz.history[q.id]={choice,blank:false,correct:ok};persist()}
function markStatus(status){const q=quiz.pool[quiz.index],p=progressFor(q.id);p.status=status;userState().progress[q.id]=p;persist();notify(`Segnata: ${statusLabel(status)}`);next()}
function skip(){const q=quiz.pool[quiz.index];if(quiz.kind==='study'){const p=progressFor(q.id);if(!quiz.history[q.id])p.skipped++;p.status='unanswered';p.lastAt=new Date().toISOString();userState().progress[q.id]=p;quiz.history[q.id]={choice:null,blank:true,correct:false};persist();next()}else{quiz.selected=null;examNext()}}
function previous(){if(quiz.index<=0)return;if(quiz.kind==='exam')quiz.answers[quiz.index]=quiz.selected;quiz.index--;const q=quiz.pool[quiz.index];quiz.selected=quiz.kind==='exam'?quiz.answers[quiz.index]:(quiz.history[q.id]?.choice??null);saveActiveQuiz();renderQuestion()}
function next(){quiz.index++;quiz.selected=null;if(quiz.index>=quiz.pool.length)return finishStudy();const q=quiz.pool[quiz.index];quiz.selected=quiz.history[q.id]?.choice??null;renderQuestion()}
function finishStudy(){if(!quiz||quiz.finished)return;quiz.finished=true;const rows=quiz.pool.map(q=>quiz.history[q.id]||{choice:null,blank:true,correct:false,q}),correct=rows.filter(x=>x.correct).length,wrong=rows.filter(x=>!x.correct&&!x.blank).length,blank=rows.filter(x=>x.blank).length,score=scoreFor(correct,wrong);userState().sessions.push({type:'study',at:new Date().toISOString(),correct,wrong,blank,score});persist();app.innerHTML=resultCard('Quiz completato',correct,wrong,blank,'<a class="button primary" href="#categories">Materie</a><a class="button ghost" href="#stats">Progressi</a>')+reviewReport(rows);window.scrollTo({top:0,behavior:'instant'})}
const statusLabel=s=>({known:'La so',review:'Da ripetere',unknown:'Non la so',unanswered:'Non risposta'}[s]||'Non risposta');

function simulationView(){nav('simulation');app.innerHTML=`<div class="section-head"><div><div class="eyebrow">Prove da 40 domande</div><h1>Scegli la modalità</h1></div></div><div class="card"><h2>Simulazione a tempo</h2><p>40 domande in 40 minuti. Nessuna correzione durante la prova.</p><div class="exam-rule"><strong>+1</strong><span>Corretta</span></div><div class="exam-rule"><strong>−0,33</strong><span>Errata</span></div><div class="exam-rule"><strong>0</strong><span>Non data</span></div><button class="primary exam-start" data-start-exam>Avvia simulazione 40/40</button></div><div class="card composition guided-exam-card"><h2>Prova guidata con spiegazioni</h2><p>Stesse 40 domande e stessa composizione, ma dopo ogni risposta vedi subito esito, soluzione corretta e spiegazione.</p><button class="secondary" data-start-guided-exam>Avvia prova guidata da 40</button></div><div class="card composition"><h2>Composizione identica per entrambe</h2><p><b>8</b> Storia · <b>11</b> Logica · <b>1</b> Insiemi · <b>6</b> Fisica · <b>6</b> Chimica · <b>4</b> Informatica · <b>4</b> Inglese</p></div>`;app.querySelector('[data-start-exam]').onclick=startExam;app.querySelector('[data-start-guided-exam]').onclick=startGuidedExam}
function startGuidedExam(){const seed=createQuizSeed('guided-exam'),plan=examPlan(),selected=plan.flatMap(([cat,count])=>takeGuidedComposition(cat,count,seed)),pool=shuffleWithSeed(selected,`${seed}|questions`).map(q=>shuffleGuidedAnswers(q,`${seed}|answers|${q.id}`));userState().examCount++;persist();quiz={kind:'guided',mode:'guided-exam',pool,index:0,history:{},selected:null,remaining:EXAM_SECONDS,startedAt:Date.now(),generatedAt:new Date().toISOString()};saveActiveQuiz();renderGuided();startFortyMinuteTimer()}
function takeGuidedComposition(cat,count,seed){const all=allQuestions().filter(q=>q.category===cat),withExplanation=all.filter(q=>q.explanation),source=withExplanation.length>=count?withExplanation:all;return takeRotating(source,count,'guided-exam',cat,seed)}
function startExam(){const seed=createQuizSeed('exam'),plan=examPlan(),selected=plan.flatMap(([cat,count])=>takeRotating(allQuestions().filter(q=>q.category===cat),count,'exam',cat,seed)),pool=shuffleWithSeed(selected,`${seed}|questions`);userState().examCount++;persist();quiz={kind:'exam',pool,index:0,answers:Array(pool.length).fill(null),selected:null,remaining:EXAM_SECONDS,startedAt:Date.now(),generatedAt:new Date().toISOString()};saveActiveQuiz();renderQuestion();startFortyMinuteTimer()}
function examNext(){quiz.answers[quiz.index]=quiz.selected;quiz.index++;quiz.selected=null;if(quiz.index>=quiz.pool.length)return finishExam();saveActiveQuiz();renderQuestion()}
function finishExam(){clearInterval(timerHandle);if(!quiz||quiz.finished)return;quiz.finished=true;const rows=quiz.pool.map((q,i)=>({id:q.id,category:q.category,q,choice:quiz.answers[i],correct:quiz.answers[i]===q.correct,blank:quiz.answers[i]===null}));let correct=0,wrong=0,blank=0;for(const r of rows){const p=progressFor(r.id);if(r.blank){blank++;p.skipped++;if(!p.attempts)p.status='unanswered'}else{p.attempts++;if(r.correct){correct++;p.correct++;p.status=p.correct>=2&&p.wrong===0?'known':'review'}else{wrong++;p.wrong++;p.status='unknown'}}p.lastAt=new Date().toISOString();userState().progress[r.id]=p}const score=Math.round((correct-wrong*.33)*100)/100;userState().sessions.push({type:'exam',at:new Date().toISOString(),correct,wrong,blank,score});persist();app.innerHTML=`<div class="result-card card"><div class="eyebrow">Simulazione completata</div><h1>${score.toLocaleString('it')} punti</h1><div class="stat-row"><div class="stat"><strong>${correct}</strong><span>Corrette</span></div><div class="stat"><strong>${wrong}</strong><span>Errate</span></div><div class="stat"><strong>${blank}</strong><span>Non date</span></div></div><p class="meta">Calcolo: ${correct} − (${wrong} × 0,33) = ${score.toLocaleString('it')}</p><div class="quiz-actions"><a class="button primary" href="#simulation">Nuova prova</a><a class="button ghost" href="#stats">Statistiche</a></div></div>${reviewReport(rows)}`}
function reviewReport(rows){if(!rows.length)return'';const group=(type,label)=>{const list=rows.filter(r=>type==='correct'?r.correct:type==='wrong'?!r.correct&&!r.blank:r.blank);return `<section class="review-group"><div class="section-head"><h2>${label}</h2><span class="review-count">${list.length}</span></div>${list.length?list.map((r,i)=>{const q=r.q,chosen=r.blank?'Non data':q.answers[r.choice],right=q.answers[q.correct];return `<details class="card review-item" ${type==='wrong'?'open':''}><summary><span class="review-badge ${type}">${type==='correct'?'✓':type==='wrong'?'✕':'—'}</span><span>${esc(q.text)}</span></summary>${q.image?`<img class="question-image mini" src="${esc(q.image)}" alt="Diagramma del quesito">`:''}<div class="review-answer"><span>La tua risposta</span><b>${esc(chosen)}</b></div><div class="review-answer correct-text"><span>Risposta corretta</span><b>${esc(right)}</b></div><div class="review-explanation"><span>Spiegazione</span><p>${q.explanation?esc(q.explanation):'Non disponibile nel dataset attuale.'}</p></div></details>`}).join(''):'<div class="card meta">Nessuna domanda.</div>'}</section>`};return `<div class="review-report"><div class="section-head"><div><div class="eyebrow">Correzione completa</div><h1>Rivedi tutte le risposte</h1></div></div>${group('wrong','Risposte errate')}${group('blank','Non risposte')}${group('correct','Risposte corrette')}</div>`}
const formatTime=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;

function statsView(){nav('stats');const s=summary(),total=allQuestions().length,exams=userState().sessions.filter(x=>x.type==='exam');app.innerHTML=`<div class="section-head"><div><div class="eyebrow">Profilo personale</div><h1>Progressi</h1></div></div><div class="stat-row four"><div class="card stat"><strong>${s.known}</strong><span class="meta">Le so</span></div><div class="card stat"><strong>${s.review}</strong><span class="meta">Ripetere</span></div><div class="card stat"><strong>${s.unknown}</strong><span class="meta">Non so</span></div><div class="card stat"><strong>${total-s.answered}</strong><span class="meta">Mai fatte</span></div></div><div class="section-head"><h2>Per materia</h2></div>${categories.map(c=>{const qs=allQuestions().filter(q=>q.category===c.id),done=qs.filter(q=>progressFor(q.id).attempts).length,p=Math.round(done/qs.length*100);return `<a class="card stat-line" href="#category/${c.id}"><b>${c.name}</b><span>${done}/${qs.length} · ${p}%</span><div class="progress"><span style="width:${p}%"></span></div></a>`}).join('')}<div class="section-head"><h2>Ultime simulazioni</h2></div>${exams.length?exams.slice(-5).reverse().map(x=>`<div class="card history"><b>${new Date(x.at).toLocaleDateString('it')}</b><span>${x.score} punti · ${x.correct}✓ ${x.wrong}✕ ${x.blank}—</span></div>`).join(''):'<div class="card meta">Nessuna simulazione completata.</div>'}`}

function adminView(){if(currentUser.role!=='admin')return home();nav('admin');app.innerHTML=`<div class="section-head"><div><div class="eyebrow">Solo amministratori</div><h1>Gestione utenti</h1></div></div><form class="card admin-form" id="newUser"><h2>Crea utente</h2><label>Nome visualizzato<input name="name" required></label><label>Nome utente<input name="username" required></label><label>Password temporanea<input name="password" type="password" minlength="6" required></label><label>Ruolo<select name="role"><option value="user">Utente</option><option value="admin">Amministratore</option></select></label><button class="primary">Crea account</button></form><div class="section-head"><h2>Utenti (${users.length})</h2></div><div class="user-list">${users.map(u=>`<div class="card user-row"><div><b>${esc(u.name)}</b><span>@${esc(u.username)} · ${u.role}</span></div><button class="ghost compact" data-toggle="${u.id}" ${u.id===currentUser.id?'disabled':''}>${u.active?'Disattiva':'Riattiva'}</button></div>`).join('')}</div>`;app.querySelector('#newUser').onsubmit=createUser;app.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>{const u=users.find(x=>x.id===b.dataset.toggle);u.active=!u.active;saveUsers();adminView()})}
async function createUser(e){e.preventDefault();const f=new FormData(e.currentTarget),username=String(f.get('username')).trim().toLowerCase();if(users.some(u=>u.username===username))return notify('Nome utente già esistente');users.push({id:crypto.randomUUID(),username,name:String(f.get('name')).trim(),role:String(f.get('role')),passwordHash:await hash(String(f.get('password'))),createdAt:new Date().toISOString(),active:true,state:{progress:{},sessions:[],categoryCursor:{},examCursor:{},examCount:0}});saveUsers();notify('Utente creato');settingsView()}

function dataView(){nav('data');app.innerHTML=`<div class="section-head"><div><div class="eyebrow">Dataset locale</div><h1>Gestione dati</h1></div></div><div class="card data-box"><p><b>${official.length.toLocaleString('it')} quesiti ufficiali</b> caricati.</p><p class="meta">È possibile aggiungere un file JSON autorizzato con id, category, text, answers e correct.</p><input type="file" id="file" accept="application/json,.json"><button class="primary" data-import>Importa dataset</button><button class="ghost" data-clear>Rimuovi aggiunte (${imported.length})</button></div>`;app.querySelector('[data-import]').onclick=importFile;app.querySelector('[data-clear]').onclick=()=>{imported=[];localStorage.removeItem(DATA);notify('Aggiunte rimosse');dataView()}}
async function importFile(){const file=app.querySelector('#file').files[0];if(!file)return notify('Scegli un file JSON');try{const rows=JSON.parse(await file.text());if(!Array.isArray(rows)||!rows.every(q=>q.id&&categories.some(c=>c.id===q.category)&&q.text&&Array.isArray(q.answers)&&Number.isInteger(q.correct)))throw Error();imported=rows;localStorage.setItem(DATA,JSON.stringify(rows));notify(`${rows.length} quesiti importati`);dataView()}catch{notify('File non valido')}}

function enhanceTrainerCard(){app.querySelector('.guided-card')?.remove()}
const setHeaderBase=setHeader;
setHeader=function(){setHeaderBase();if(currentUser&&!document.querySelector('[data-close-app]')){const button=document.createElement('button');button.className='ghost compact close-app';button.dataset.closeApp='';button.textContent='Chiudi app';button.onclick=closePortableApp;document.querySelector('.topbar').append(button)}};
async function closePortableApp(){if(!confirm('Vuoi chiudere Quiz 400 VVF 2026?'))return;try{await portableSync();const response=await fetch('./api/shutdown',{method:'POST'});if(!response.ok)throw Error();clearInterval(timerHandle);app.innerHTML='<div class="card result-card"><h1>App chiusa</h1><p>I dati sono stati salvati. Ora puoi chiudere questa scheda.</p></div>';document.querySelector('.bottom-nav').classList.add('hidden');setTimeout(()=>window.close(),500)}catch{notify('Chiusura automatica disponibile nella versione portatile')}}
const loginViewBase=loginView;
loginView=function(){loginViewBase();const label=app.querySelector('.auth-copy .eyebrow');if(label)label.textContent='Quiz 400 VVF 2026'};
const simulationViewBase=simulationView;
simulationView=function(){nav('simulation');if(resumeActiveQuiz())return;const composition=examPlan().map(([id,n])=>`<b>${n}</b> ${esc(catName(id))}`).join(' · ');app.innerHTML=`<div class="section-head"><div><div class="eyebrow">Prove da 40 domande</div><h1>Scegli la modalità</h1></div></div><div class="card rotation-card"><h2>Estrazione sempre nuova</h2><p>Ogni prova usa data e ora correnti per mescolare le 40 domande. La rotazione viene salvata: anche dopo aver chiuso e riaperto l’app non riparte dallo stesso quiz e non ripete i quesiti già estratti finché la materia non completa il proprio ciclo.</p></div><div class="card"><h2>Simulazione a tempo</h2><p>40 domande in 40 minuti, con cronometro sempre visibile e consegna automatica allo scadere. Nessuna correzione durante la prova.</p><div class="exam-rule"><strong>+1</strong><span>Corretta</span></div><div class="exam-rule"><strong>−0,33</strong><span>Errata</span></div><div class="exam-rule"><strong>0</strong><span>Non data</span></div><button class="primary exam-start" data-start-exam>Avvia simulazione 40/40</button></div><div class="card composition guided-exam-card"><h2>Prova guidata con spiegazioni</h2><p>Stesse 40 domande, stesso cronometro di 40 minuti, con esito, soluzione e spiegazione immediati.</p><button class="secondary" data-start-guided-exam>Avvia prova guidata da 40</button></div><div class="card composition"><h2>Composizione attuale</h2><p>${composition}</p>${currentUser.role==='admin'?'<a class="button ghost" href="#settings">Modifica composizione</a>':''}</div>`;app.querySelector('[data-start-exam]').onclick=startExam;app.querySelector('[data-start-guided-exam]').onclick=startGuidedExam};
function settingsView(){if(currentUser.role!=='admin')return home();nav('settings');const total=examPlan().reduce((sum,[,n])=>sum+n,0);app.innerHTML=`<div class="section-head"><div><div class="eyebrow">Solo amministratori</div><h1>Impostazioni</h1></div></div><form class="card admin-form" id="examSettings"><h2>Composizione delle 40 domande</h2><p class="meta">Imposta 0 per togliere una materia. La somma deve essere esattamente 40.</p>${categories.map(c=>`<label>${esc(c.name)}<input type="number" min="0" max="40" step="1" name="${c.id}" value="${Number(examConfig.examPlan?.[c.id])||0}"></label>`).join('')}<div class="settings-total">Totale attuale: <strong data-settings-total>${total}</strong>/40</div><div class="quiz-actions"><button class="primary" type="submit">Salva composizione</button><button class="ghost" type="button" data-reset-plan>Ripristina predefinita</button></div></form>`;const form=app.querySelector('#examSettings'),update=()=>app.querySelector('[data-settings-total]').textContent=[...form.querySelectorAll('input')].reduce((s,x)=>s+(Number(x.value)||0),0);form.querySelectorAll('input').forEach(x=>x.addEventListener('input',update));form.onsubmit=e=>{e.preventDefault();const values=Object.fromEntries(categories.map(c=>[c.id,Math.max(0,Math.floor(Number(new FormData(form).get(c.id))||0))])),sum=Object.values(values).reduce((a,b)=>a+b,0);if(sum!==40)return notify(`Il totale deve essere 40: ora è ${sum}`);examConfig={...examConfig,examPlan:values};localStorage.setItem(CONFIG,JSON.stringify(examConfig));portableSync();notify('Composizione salvata');routeTo('simulation')};app.querySelector('[data-reset-plan]').onclick=()=>{examConfig={...examConfig,examPlan:{...DEFAULT_EXAM_PLAN}};localStorage.setItem(CONFIG,JSON.stringify(examConfig));portableSync();settingsView()}};
const settingsViewBase=settingsView;
function userSettingsMarkup(){return `<section class="settings-users"><div class="section-head"><div><div class="eyebrow">Percorsi personali separati</div><h2>Utenti e statistiche</h2></div><span class="review-count">${users.length}</span></div><div class="card user-privacy-note"><b>Ogni utente ha il proprio percorso</b><p class="meta">Domande svolte, classificazione “La so / Da ripetere / Non la so”, rotazione dei quiz, simulazioni e punteggi sono salvati separatamente per ogni account.</p></div><form class="card admin-form" id="settingsNewUser"><h2>Crea utente</h2><label>Nome visualizzato<input name="name" required></label><label>Nome utente<input name="username" required></label><label>Password temporanea<input name="password" type="password" minlength="6" required></label><label>Ruolo<select name="role"><option value="user">Utente</option><option value="admin">Amministratore</option></select></label><button class="primary">Crea account</button></form><div class="user-list settings-user-list">${users.map(u=>{const progress=Object.values(u.state?.progress||{}),answered=progress.filter(item=>item.attempts).length,known=progress.filter(item=>item.status==='known').length,exams=(u.state?.sessions||[]).filter(item=>item.type==='exam').length;return `<div class="card user-row settings-user-row"><div><b>${esc(u.name)} ${u.id===currentUser.id?'<small class="current-user-label">Account attuale</small>':''}</b><span>@${esc(u.username)} · ${u.role==='admin'?'Amministratore':'Utente'} · ${u.active?'Attivo':'Disattivato'}</span><span class="user-progress-line"><strong>${answered}</strong> svolte · <strong>${known}</strong> conosciute · <strong>${exams}</strong> simulazioni</span></div><button class="ghost compact" data-settings-toggle="${u.id}" ${u.id===currentUser.id?'disabled':''}>${u.active?'Disattiva':'Riattiva'}</button></div>`}).join('')}</div></section>`}
settingsView=function(){settingsViewBase();if(currentUser.role!=='admin')return;app.querySelector('#examSettings')?.insertAdjacentHTML('afterend','<div class="card backup-card"><h2>Backup e ripristino</h2><p class="meta">Esporta utenti, progressi, statistiche, impostazioni e dataset importati in un unico file.</p><div class="quiz-actions"><button class="secondary" type="button" data-export-backup>Scarica backup</button><label class="button ghost backup-file">Ripristina backup<input type="file" accept="application/json,.json" data-restore-backup hidden></label></div></div>');const anchor=app.querySelector('.backup-card')||app.querySelector('#examSettings');anchor?.insertAdjacentHTML('afterend',userSettingsMarkup());app.querySelector('[data-export-backup]')?.addEventListener('click',exportBackup);app.querySelector('[data-restore-backup]')?.addEventListener('change',restoreBackup);app.querySelector('#settingsNewUser')?.addEventListener('submit',createUser);app.querySelectorAll('[data-settings-toggle]').forEach(button=>button.onclick=()=>{const user=users.find(item=>item.id===button.dataset.settingsToggle);user.active=!user.active;saveUsers();settingsView()})};
function exportBackup(){const payload={app:'Quiz 400 VVF 2026',version:1,createdAt:new Date().toISOString(),users,imported,config:examConfig},blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`quiz-400-vvf-2026-backup-${new Date().toISOString().slice(0,10)}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('Backup creato')}
async function restoreBackup(e){const file=e.target.files?.[0];if(!file)return;try{const backup=JSON.parse(await file.text()),plan=backup.config?.examPlan,total=plan&&Object.values(plan).reduce((s,n)=>s+(Number(n)||0),0);if(backup.app!=='Quiz 400 VVF 2026'||!Array.isArray(backup.users)||!Array.isArray(backup.imported)||!plan||total!==40)throw Error();if(!confirm('Il ripristino sostituirà utenti, progressi, statistiche e impostazioni attuali. Continuare?')){e.target.value='';return}users=backup.users;imported=backup.imported;examConfig=backup.config;localStorage.setItem(USERS,JSON.stringify(users));localStorage.setItem(DATA,JSON.stringify(imported));localStorage.setItem(CONFIG,JSON.stringify(examConfig));await portableSync();alert('Backup ripristinato correttamente. L’app verrà ricaricata.');location.reload()}catch{e.target.value='';notify('Backup non valido o danneggiato')}}
const adminViewBase=adminView;
adminView=function(){if(currentUser.role!=='admin')return home();routeTo('settings')};
const renderGuidedBase=renderGuided;
renderGuided=function(){renderGuidedBase();const h=quiz?.pool?.[quiz.index]&&quiz.history[quiz.pool[quiz.index].id];if(!h)return;const bottomNav=app.querySelector('.nav-actions'),feedback=app.querySelector('.trainer-feedback');if(!bottomNav)return;const topNav=bottomNav.cloneNode(true);topNav.classList.add('explanation-nav','top');feedback?feedback.before(topNav):bottomNav.before(topNav);topNav.querySelector('[data-guided-prev]')?.addEventListener('click',guidedPrevious);topNav.querySelector('[data-guided-next]')?.addEventListener('click',guidedNext)};
const scoreFor=(correct,wrong)=>Math.round((correct-wrong*.33)*100)/100;
function resultCard(title,correct,wrong,blank,actions){const score=scoreFor(correct,wrong);return `<div class="result-card card"><div class="eyebrow">${esc(title)}</div><div class="result-score-label">Punteggio finale</div><h1 class="result-score">${score.toLocaleString('it')} punti</h1><div class="stat-row"><div class="stat correct-stat"><strong>${correct}</strong><span>Corrette</span></div><div class="stat wrong-stat"><strong>${wrong}</strong><span>Errate</span></div><div class="stat blank-stat"><strong>${blank}</strong><span>Non risposte</span></div></div><p class="score-formula">Calcolo: ${correct} - (${wrong} × 0,33) = <b>${score.toLocaleString('it')}</b></p><div class="quiz-actions">${actions}</div></div>`}
const resultCardBase=resultCard;
resultCard=function(title,correct,wrong,blank,actions){const safeActions=actions.replaceAll('href="#simulation"','href="#simulation/new"').replaceAll('href="#categories"','href="#categories/new"');return resultCardBase(title,correct,wrong,blank,safeActions)};
reviewReport=function(rows){if(!rows.length)return'';const counts={wrong:rows.filter(r=>!r.correct&&!r.blank).length,blank:rows.filter(r=>r.blank).length,correct:rows.filter(r=>r.correct).length},group=(type,label)=>{const list=rows.filter(r=>type==='correct'?r.correct:type==='wrong'?!r.correct&&!r.blank:r.blank);return `<section class="review-group" id="review-${type}"><div class="section-head"><h2>${label}</h2><span class="review-count">${list.length}</span></div>${list.length?list.map((r,i)=>{const q=r.q||allQuestions().find(x=>x.id===r.id),chosen=r.blank?'Non data':q.answers[r.choice],right=q.answers[q.correct],explanation=q.explanation||'Spiegazione non disponibile per questo quesito.';return `<details class="card review-item" ${type!=='correct'?'open':''}><summary><span class="review-badge ${type}">${type==='correct'?'✓':type==='wrong'?'✕':'—'}</span><span><small>${esc(catName(q.category))} · domanda ${i+1}</small>${esc(q.text)}</span></summary>${q.image?`<img class="question-image mini" src="${esc(q.image)}" alt="Diagramma del quesito">`:''}<div class="review-answer"><span>La tua risposta</span><b>${esc(chosen)}</b></div><div class="review-answer correct-text"><span>Risposta corretta</span><b>${esc(right)}</b></div><div class="review-explanation"><span>Spiegazione</span><div class="explanation-copy">${esc(explanation)}</div></div></details>`}).join(''):'<div class="card meta">Nessuna domanda.</div>'}</section>`};return `<div class="review-report"><div class="section-head"><div><div class="eyebrow">Correzione completa</div><h1>Cosa hai sbagliato, saltato o risposto bene</h1></div></div><div class="review-tabs"><a href="#review-wrong" class="wrong">${counts.wrong} errate</a><a href="#review-blank" class="blank">${counts.blank} non risposte</a><a href="#review-correct" class="correct">${counts.correct} corrette</a></div>${group('wrong','Risposte errate')}${group('blank','Non risposte')}${group('correct','Risposte corrette')}</div>`};
finishGuided=function(reason='completed'){clearInterval(timerHandle);if(!quiz||quiz.finished)return;quiz.finished=true;const rows=quiz.pool.map(q=>quiz.history[q.id]||{choice:null,blank:true,correct:false,q});if(reason==='timeout'){for(const row of rows.filter(item=>item.blank&&!quiz.history[item.q.id])){const p=progressFor(row.q.id);p.skipped++;if(!p.attempts)p.status='unanswered';p.lastAt=new Date().toISOString();userState().progress[row.q.id]=p}}const correct=rows.filter(x=>x.correct).length,wrong=rows.filter(x=>!x.correct&&!x.blank).length,blank=rows.filter(x=>x.blank).length,score=scoreFor(correct,wrong);userState().sessions.push({type:'guided',at:new Date().toISOString(),correct,wrong,blank,score,timedOut:reason==='timeout'});isTimedFortyQuiz()?clearActiveQuiz():persist();app.innerHTML=resultCard(reason==='timeout'?'Tempo scaduto · prova guidata conclusa':'Prova guidata completata',correct,wrong,blank,'<a class="button primary" href="#simulation">Nuova prova</a><a class="button ghost" href="#stats">Statistiche</a>')+reviewReport(rows);window.scrollTo({top:0,behavior:'instant'})};
finishStudy=function(){if(!quiz||quiz.finished)return;quiz.finished=true;const rows=quiz.pool.map(q=>quiz.history[q.id]||{choice:null,blank:true,correct:false,q}),correct=rows.filter(x=>x.correct).length,wrong=rows.filter(x=>!x.correct&&!x.blank).length,blank=rows.filter(x=>x.blank).length,score=scoreFor(correct,wrong);userState().sessions.push({type:'study',at:new Date().toISOString(),correct,wrong,blank,score});persist();app.innerHTML=resultCard('Quiz completato',correct,wrong,blank,'<a class="button primary" href="#categories">Materie</a><a class="button ghost" href="#stats">Progressi</a>')+reviewReport(rows);window.scrollTo({top:0,behavior:'instant'})};
finishExam=function(reason='completed'){clearInterval(timerHandle);if(!quiz||quiz.finished)return;quiz.finished=true;const rows=quiz.pool.map((q,i)=>({id:q.id,category:q.category,q,choice:quiz.answers[i],correct:quiz.answers[i]===q.correct,blank:quiz.answers[i]===null}));let correct=0,wrong=0,blank=0;for(const r of rows){const p=progressFor(r.id);if(r.blank){blank++;p.skipped++;if(!p.attempts)p.status='unanswered'}else{p.attempts++;if(r.correct){correct++;p.correct++;p.status=p.correct>=2&&p.wrong===0?'known':'review'}else{wrong++;p.wrong++;p.status='unknown'}}p.lastAt=new Date().toISOString();userState().progress[r.id]=p}const score=scoreFor(correct,wrong);userState().sessions.push({type:'exam',at:new Date().toISOString(),correct,wrong,blank,score,timedOut:reason==='timeout'});clearActiveQuiz();app.innerHTML=resultCard(reason==='timeout'?'Tempo scaduto · simulazione conclusa':'Simulazione completata',correct,wrong,blank,'<a class="button primary" href="#simulation">Nuova prova</a><a class="button ghost" href="#stats">Statistiche</a>')+reviewReport(rows);window.scrollTo({top:0,behavior:'instant'})};
function router(){if(!currentUser)return loginView();document.querySelector('.bottom-nav').classList.remove('hidden');setHeader();const [route,param]=location.hash.slice(1).split('/'),handler=({home,categories:categoriesView,category:()=>categoryView(param),stats:statsView,simulation:simulationView,review:()=>reviewView(param),admin:adminView,settings:settingsView,data:dataView}[route]||home);handler();enhanceTrainerCard()}
window.addEventListener('hashchange',router);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;document.querySelector('#installBtn').classList.remove('hidden')});document.querySelector('#installBtn').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null}};
if('serviceWorker'in navigator){const hadController=Boolean(navigator.serviceWorker.controller);navigator.serviceWorker.register('./sw.js').then(()=>{let refreshing=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(hadController&&!refreshing){refreshing=true;location.reload()}})}).catch(()=>{})}
app.innerHTML='<div class="card">Caricamento banca dati…</div>';
fetch('./api/state').then(r=>r.ok?r.json():Promise.reject()).then(state=>{if(Array.isArray(state.users)){users=state.users;localStorage.setItem(USERS,JSON.stringify(users))}if(Array.isArray(state.imported)){imported=state.imported;localStorage.setItem(DATA,JSON.stringify(imported))}if(state.config?.examPlan){examConfig=state.config;localStorage.setItem(CONFIG,JSON.stringify(examConfig))}}).catch(()=>{}).then(()=>fetch('./quiz-dataset.json')).then(r=>r.json()).then(rows=>{official=rows;const id=sessionStorage.getItem(SESSION),u=users.find(x=>x.id===id&&x.active);if(u)currentUser={id:u.id,name:u.name,role:u.role};router();if(u)checkForUpdates(false)}).catch(()=>app.innerHTML='<div class="notice">Impossibile caricare la banca dati.</div>');
